runtime: nodejs22
instance_class: F1
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic

inbound_services:
- warmup

liveness_check:
  path: /health
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2

readiness_check:
  path: /readiness
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2